name: Test Nomos E2E Tests Daily

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - chore-sharding-github-workflows
jobs:
  test-common:
    uses: ./.github/workflows/test_common.yml

